### ISSUE TITLE
文本溢出

### ISSUE THREAD

**Issue by baiziyu-fe** [baiziyu-fe/CSS#1]
1. 单行省略
```CSS
{
    width: 200px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
2. 多行省略
```CSS
{
    width: 200px;
    overflow : hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
```
3. 超长文本整块省略
```CSS
{
    width: 200px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
4. 超长文本多余块内容省略
```
只需要将包裹整块标签元素的 span 的 display 由 inline 改为 inline-block 即可
```
